### ISSUE TITLE
On 17.10 attempt to install 4.13.4 kernel results in error

### ISSUE THREAD

**Issue by jerdog** [teejee2008/ukuu#25] opened 2017-10-04 16:02 UTC
Using the CLI the following error is received:
```
$ sudo ukuu --install 4.13.4
[sudo] password for : 
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused

(ukuu:7669): Gtk-WARNING **: cannot open display: :0
```

**Comment by rosterloh** [comment] 2017-10-12 11:30
Same here for 4.13.6. Must be a Wayland issue

**Comment by fuelflo** [comment] 2017-10-14 18:16
possible related to: #13 
have the same problem using ukuu on wayland.

**Comment by jignesh248** [comment] 2017-10-23 15:22
same issues after updating ubuntu to 17.10 i.e. wayland

**Comment by kseyhan** [comment] 2017-10-27 14:23
check my proposed solution at [#13](https://github.com/teejee2008/ukuu/issues/13)

**Comment by jgoodleaf** [comment] 2017-10-31 19:59
@kseyhan 's solution works, though you probably shouldn't leave `xhost +` enabled.

**Comment by fgblomqvist** [comment] 2017-10-31 23:43
I am running Ubuntu 17.10, but using the Xorg session, and can successfully install kernels. As in, this must be a Wayland issue.

**Comment by kseyhan** [comment] 2017-11-02 17:39
yes thats right @jgoodleaf use 

`xhost -`

after youre finished.

**Comment by craigcarnell** [comment] 2017-12-12 11:31
Any idea when wayland will be supported?

**Comment by teejee2008** [comment] 2017-12-16 06:12
Duplicate of #9

**Closed by teejee2008** 2017-12-16 06:12 UTC
