### ISSUE TITLE
Feature Request for "low latency", Real Time RT, and LTS kernels and questions

### ISSUE THREAD

**Issue by phd21** [teejee2008/ukuu#28] opened 2017-12-02 19:07 UTC
Dear teejee2008, 

First, I love a lot of your applications, including Ukuu. Thank you so much for providing these for all of us.

I do not know if this request should be part of a couple other requests I see in this.

Can you add or modify Ukuu to show and use  "low-latency" Kernels in addition to LTS and Real Time (RT) Kernels?

Out of curiosity, why wouldn't everyone want a low-latency or Real Time (RT) Kernel? Why is that not the default for Linux Kernels? Which is better Low-Latency or RT Kernel?

Best regards to you and yours,
Phil
phd21

**Comment by teejee2008** [comment] 2017-12-16 04:41
RT and LT kernels are for very specialized use-cases. They are not meant for general desktop use. They are meant for systems that connect to hardware that require low-latency - like audio recording equipment, etc. I don't want to add this to Ukuu because people may end up installing the kernels thinking that they are "faster", and run into issues.

**Comment by teejee2008** [comment] 2017-12-16 06:09
Duplicate of #5

**Closed by teejee2008** 2017-12-16 06:09 UTC

**Comment by AstralStorm** [comment] 2018-10-22 13:47
This is dumb. If they were so "specialized", Ubuntu wouldn't make them. And lowlatency kernel is stable and released *for every Ubuntu release*.

**Comment by teejee2008** [comment] 2018-10-23 06:18
Canonical makes these kernels available because they are easy to make. The kernels are built by automated build systems and doesn't require any additional work.
I'm not saying that the lowlatency kernels are useless. I'm saying that it is not suitable for general use (my opinion) and that I won't be providing support for it (since I will have to do the work).
