### ISSUE TITLE
Ukuu Doesn't Provide A Kernel Type Setting

### ISSUE THREAD

**Issue by voice06** [teejee2008/ukuu#2] opened 2017-03-31 18:45 UTC
More of a feature request than a bug.

As the title says, at the present time Ukuu doesn't provide a list of kernel types to chose from via settings, instead it is hard-coded to use -generic which is fine for most people. That said, it would be nice to be able to tell Ukuu I want the -lowlatency kernel instead of the -generic kernel.

**Comment by teejee2008** [comment] 2017-12-16 06:09
Duplicate of #5

**Closed by teejee2008** 2017-12-16 06:09 UTC
Labels: enhancement
